### ISSUE TITLE
Buffer transaction not being spent

### ISSUE THREAD

**Issue by bonomat** [get10101/10101#1466]
We broadcasted a buffer transaction: 
```
{"timestamp":"2023-10-02T02:14:43.016222745Z","level":"INFO","fields":{"message":"Broadcasting transaction","txid":"b3c25a131236343700b244eea12bffb4624902ca55ff822dd6ad1a8bfa2aaeb7","raw_tx":"02000000000101836db9b3a2149248ece5fd21f1df49ad4d0b219d3a141a89add9105089427ecc0100000000200100000180ca000000000000220020773d49432b33774b6d79c6707390f8f28877c45b70f7b6481e4d91967f48e7c10347304402207bc9f864b053c2e56d55bcf07cf2b91aa9f5352ddf9bd3169222550c1f31dbc10220632e88dd957c35829eb4f3b0afd3af55c276b121f72d6d2bb34bcc98a7f4fc5801483045022100da369d1375c89047a26fba2f327535c26074ebe96242fc929826da5acc0afd3802200772f77a507e0374736b9d1866c0b945d767efc3931c894e132718bd45371e4201e021036b16dd21bcc6701f01d97640255f0f6ba90837046e68a2b5a52b7091ee976077ac646376a914821012e962b5c5d3912cdff4645dcb347109be9e88ad76a914c3ee0f3f908c0d87676de9fcd4274b87ae1625b588ad76a9148a725afb4c047ee9dd5e1ce4122937061f5b251c886776a91476d3d13df87902a1944d6d0ef4bd6ac73553662888ad76a9140357b09b5be63cf886ba023aa3af5e34443113e588ad76a914c493153d44c7cf491a51f27ed9cf35bfc62811168868672103a4e12b710977423a595a7eca2ce0fe9c697224b3e1c021cd355929d9f1bf705168ac827fc764"},"target":"ln_dlc_node::ldk_node_wallet"}
```

```
{"timestamp":"2023-10-09T15:52:15.163627927Z","level":"INFO","fields":{"message":"Buffer transaction for contract 419f7e8bec0529ea4c36d86e413e8c1c011cfb6fa48bf5d2977bb80ddcb4d855 has enough confirmations to spend from it","log.target":"dlc_manager::manager","log.module_path":"dlc_manager::manager","log.file":"/home/runner/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/9815582/dlc-manager/src/manager.rs","log.line":1134},"target":"dlc_manager::manager"}
```

And tried to spend from it but fail: 

```
{"timestamp":"2023-10-09T15:52:15.340323107Z","level":"INFO","fields":{"message":"Broadcasting transaction","txid":"a71453181927daf76bf9eeb9be0852e8d384ebdce4b9dea34bc02f2afee35e11","raw_tx":"02000000000101b7ae2afa8b1aadd62d82ff55ca024962b4ff2ba1ee44b20037343612135ac2b300000000002001000001b0c5000000000000160014811647de45e1fbae4531db37077f1c011bc7c2420347304402205f1ef42354f0c46af379b1c0c41f5c6c2427fe306105825a6e28e63d6a48951302201aa2fb24655826a8ea8288b323c5f773d0a91f056c312ab83ae07e84d1b96e9d01473044022059618b3e72212482ba212f493b98b645b3fd6e8c7c1a41cdc8be5d06e1b44d89022076829d02a702e314132ec8099d14ca6ce1c464f47434f669bdd34a3726302bcd01e02102117c0f9329cb2feeee13106118837927224b9ea14eafc4a3c9d27624f503b3fdac646376a9143a3db03d2122f1afd9e71d3baeb8eea155acac0588ad76a914c3ce98b84de36acdc067da8eaf7dcd69b23483f888ad76a9141b805505c3e23d5264eeb3f31568c6b47d97a96f886776a914dd3e055f729f3696e302e8df678490794db96cfb88ad76a91414ca2b99cee3a39408aa187f3198f485d8daf00488ad76a914730167aebecc3b653ccb73fcb25ef96c5bf4a2b18868672103578cb9200fb4d94ebd084c16fd580c418fe083d9e36e1d571178dde04217025b68ac827fc764"},"target":"ln_dlc_node::ldk_node_wallet"}
```

It looks like we constructed an invalid CET.

**Comment by holzeis** [comment]
Reproduced on the latest main

```
2023-11-16 13:00:51  INFO dlc_manager::manager: Buffer transaction for contract 66e5200035982870036d061b59157d7f856f74077496cdd7829dff0e47ea6390 has enough confirmations to spend from it    
2023-11-16 13:00:51 DEBUG reqwest::connect: starting new connection: http://localhost:8081/    
2023-11-16 13:00:51  INFO ln_dlc_node::ldk_node_wallet: Broadcasting transaction txid=e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5 raw_tx=020000000001017601004a203c1856e61bda3bdbd8d411b632c0d34f6efacc93ef59fec86c791e000000000020010000026a31000000000000160014fc9dbf9f258091ca8f3677bd05615a1339702a6a7c37000000000000160014d9c449146b6e77fb25e1a0cb9df8a4f1bfb76b9f0347304402200ab63a163bbd8b686ed14255780457e263a41113428008af50b61db364aed150022057400cde7630c0442c751156e1cee55629105512edc8c1e011cd18a6202d6ec201483045022100a28aa34005aa993147a38a03244696506958d7a4fec5e1f2c36b6756007733df0220267d2991388fec96f00ed97db2fbc33371f493af2a0896ece4f9248757cdc94501e021025931a2e3f4f7d56d0257dc5fdd82d2d37c8b593a0ddd1daba79a7002a01ea7cdac646376a91455780dc712c2f1826a1e7d19324bb499c535d56488ad76a914154e89e8f2f82a3dc996e78122f756c0db1e2e3288ad76a9148fef66593ad2cb3d652e6ee8b2b56f928c0dcfe0886776a914ee6e7d71ca580fc8e54995842e4d9e4ca2dfd24d88ad76a914e3e29723c6fd4a7e1647d5995875fcafc484558b88ad76a914e09640febf6b4b1fceb561b51e757cda1fbb39ea8868672103c3b7f1367298c06c68d46d02bb7e449b26688c7ef57a6720b7218f753069cf8a68acb9105665
2023-11-16 13:00:52 ERROR dlc_manager::manager: Error trying to close established channel: Wallet error Failed to broadcast transaction e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5    
2023-11-16 13:00:53  INFO dlc_manager::chain_monitor: Transaction e146d889dea655b11af4d2d07da01fca730376162d858e2f09903445e3b314c5 confirmed: ChannelInfo { channel_id: [230, 19, 247, 96, 242, 241, 55, 93, 104, 96, 227, 207, 95, 159, 125, 122, 149, 183, 249, 52, 117, 87, 80, 79, 4, 225, 202, 179, 96, 168, 55, 61], tx_type: Cet }    
2023-11-16 13:00:53  INFO dlc_manager::manager: Buffer transaction for contract 66e5200035982870036d061b59157d7f856f74077496cdd7829dff0e47ea6390 has enough confirmations to spend from it    
2023-11-16 13:00:53 ERROR coordinator: Aborting after panic in task info=panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/shutdown.rs:51:21
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/backtrace.rs:332:13
   3: coordinator::main::{{closure}}::{{closure}}
             at ./coordinator/src/bin/coordinator.rs:61:29
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:580:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   8: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   9: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  10: tokio::runtime::blocking::shutdown::Receiver::wait
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/shutdown.rs:51:21
  11: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:261:12
  12: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:278:9
  13: core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mod.rs:490:1
  14: core::ptr::drop_in_place<tokio::runtime::runtime::Runtime>
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ptr/mod.rs:490:1
  15: reqwest::blocking::wait::enter
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/wait.rs:76:21
  16: reqwest::blocking::wait::timeout
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/wait.rs:13:5
  17: reqwest::blocking::client::ClientHandle::new
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/client.rs:1042:15
  18: reqwest::blocking::client::ClientBuilder::build
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/client.rs:103:9
  19: reqwest::blocking::get
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/reqwest-0.11.14/src/blocking/mod.rs:107:5
  20: p2pd_oracle_client::get
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/p2pd-oracle-client/src/lib.rs:78:5
  21: <p2pd_oracle_client::P2PDOracleClient as dlc_manager::Oracle>::get_attestation
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/p2pd-oracle-client/src/lib.rs:164:13
  22: dlc_manager::manager::Manager<W,B,S,O,T,F>::get_closable_contract_info::{{closure}}
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:597:29
  23: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:298:13
  24: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/slice/iter/macros.rs:266:38
  25: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/adapters/filter_map.rs:61:9
  26: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/spec_from_iter_nested.rs:26:32
  27: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/spec_from_iter.rs:33:9
  28: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/vec/mod.rs:2712:9
  29: core::iter::traits::iterator::Iterator::collect
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/iter/traits/iterator.rs:1896:9
  30: dlc_manager::manager::Manager<W,B,S,O,T,F>::get_closable_contract_info
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:591:44
  31: dlc_manager::manager::Manager<W,B,S,O,T,F>::try_finalize_closing_established_channel
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:1178:63
  32: dlc_manager::manager::Manager<W,B,S,O,T,F>::channel_checks
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:1949:29
  33: dlc_manager::manager::Manager<W,B,S,O,T,F>::periodic_check
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/4e104b4/dlc-manager/src/manager.rs:400:9
  34: ln_dlc_node::node::manage_dlc_manager::{{closure}}
             at ./crates/ln-dlc-node/src/node/mod.rs:889:33
  35: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:296:9
  36: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  37: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  38: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  39: ___rust_try
  40: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  41: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  42: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  43: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/remote_handle.rs:105:29
  44: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  45: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  46: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  47: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  48: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  49: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  50: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  51: ___rust_try
  52: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  53: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  54: tokio::runtime::task::harness::poll_future
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  55: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  56: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  57: tokio::runtime::task::raw::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  58: tokio::runtime::task::raw::RawTask::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  59: tokio::runtime::task::LocalNotified<S>::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:394:9
  60: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:464:13
  61: tokio::runtime::coop::with_budget
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:107:5
  62: tokio::runtime::coop::budget
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/coop.rs:73:5
  63: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:463:9
  64: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:426:24
  65: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:406:17
  66: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/macros/scoped_tls.rs:61:9
  67: tokio::runtime::scheduler::multi_thread::worker::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:403:5
  68: tokio::runtime::scheduler::multi_thread::worker::block_in_place::{{closure}}::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/scheduler/multi_thread/worker.rs:343:41
  69: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  70: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  71: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  72: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  73: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  74: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  75: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  76: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  77: ___rust_try
  78: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  79: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  80: tokio::runtime::task::harness::poll_future
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  81: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  82: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  83: tokio::runtime::task::raw::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  84: tokio::runtime::task::raw::RawTask::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  85: tokio::runtime::task::UnownedTask<S>::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  86: tokio::runtime::blocking::pool::Task::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  87: tokio::runtime::blocking::pool::Inner::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  88: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  89: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  90: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:526:17
  91: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  92: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  93: ___rust_try
  94: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  95: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  96: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:525:30
  97: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  98: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  99: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
 100: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
 101: __pthread_joiner_wake

[1]    16677 abort      cargo run --bin coordinator -- 
```
