### ISSUE TITLE
Estimating fees for a transaction under dust limit does not work

### ISSUE THREAD

**Issue by Restioson** [get10101/10101#1755]
The following error is printed to the console:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, Output below the dust limit: 0, null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      WalletService.calculateFeesForOnChain (package:get_10101/features/wallet/application/wallet_service.dart:85:18)
<asynchronous suspension>
#3      _SendOnChainScreenState.build.<anonymous closure>.<anonymous closure> (package:get_10101/features/wallet/send/send_onchain_screen.dart:198:55)
<asynchronous suspension>
```

I think that this is maybe a validation error, rather: we should show some kind of error if the amount is too small, and then skip estimating the fees at that point.

**Comment by Restioson** [comment]
Oops I've just realised #1527 is not merged yet
