### ISSUE TITLE
Coordinator panics as the new block's height is not exactly one more than the last processed height

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#1991]
Just happened on the CI https://github.com/get10101/10101/actions/runs/7831872929/job/21378397855?pr=1987

```
2024-02-08 19:15:55  INFO ln_dlc_node::ldk_node_wallet: Started on-chain sync
2024-02-08 19:15:55  INFO ln_dlc_node::ldk_node_wallet: Finished on-chain sync duration=280 latest_height=113
2024-02-08 19:15:55 ERROR coordinator: Aborting after panic in task info=panicked at /home/runner/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/0786724/dlc-manager/src/chain_monitor.rs:134:9:
assertion `left == right` failed
  left: 114
 right: 113
   0: coordinator::main::{{closure}}::{{closure}}
             at ./coordinator/src/bin/coordinator.rs:65:29
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2021:9
   2: std::panicking::rust_panic_with_hook
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:735:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:609:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:170:18
   5: rust_begin_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:597:5
   6: core::panicking::panic_fmt
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:72:14
   7: core::panicking::assert_failed_inner
   8: core::panicking::assert_failed
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panicking.rs:270:5
   9: dlc_manager::chain_monitor::ChainMonitor::process_block
             at /home/runner/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/0786724/dlc-manager/src/chain_monitor.rs:134:9
  10: dlc_manager::manager::Manager<W,B,S,O,T,F>::periodic_chain_monitor
             at /home/runner/.cargo/git/checkouts/rust-dlc-b5770de66c51b951/0786724/dlc-manager/src/manager.rs:388:13
  11: ln_dlc_node::node::manage_dlc_manager::{{closure}}
             at ./crates/ln-dlc-node/src/node/mod.rs:984:33
  12: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:296:9
  13: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:42
  14: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  15: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  16: __rust_try
  17: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  18: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  19: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/catch_unwind.rs:36:9
  20: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/futures-util-0.3.28/src/future/future/remote_handle.rs:105:29
  21: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  22: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/core.rs:334:17
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/loom/std/unsafe_cell.rs:16:9
  24: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/core.rs:323:13
  25: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:485:19
  26: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  27: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  28: __rust_try
  29: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  30: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  31: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:473:18
  32: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:208:27
  33: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:153:15
  34: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/raw.rs:276:5
  35: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/raw.rs:200:18
  36: tokio::runtime::task::LocalNotified<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/mod.rs:400:9
  37: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:576:13
  38: tokio::runtime::coop::with_budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/coop.rs:107:5
  39: tokio::runtime::coop::budget
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/coop.rs:73:5
  40: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:575:9
  41: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:526:24
  42: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:491:21
  43: tokio::runtime::context::scoped::Scoped<T>::set
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/context/scoped.rs:40:9
  44: tokio::runtime::context::set_scheduler::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/context.rs:176:26
  45: std::thread::local::LocalKey<T>::try_with
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:270:16
  46: std::thread::local::LocalKey<T>::with
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/local.rs:246:9
  47: tokio::runtime::context::set_scheduler
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/context.rs:176:9
  48: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:486:9
  49: tokio::runtime::context::runtime::enter_runtime
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/context/runtime.rs:65:16
  50: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:478:5
  51: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/scheduler/multi_thread/worker.rs:447:45
  52: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/blocking/task.rs:42:21
  53: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  54: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/core.rs:334:17
  55: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/loom/std/unsafe_cell.rs:16:9
  56: tokio::runtime::task::core::Core<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/core.rs:323:13
  57: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:485:19
  58: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  59: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  60: __rust_try
  61: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  62: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  63: tokio::runtime::task::harness::poll_future
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:473:18
  64: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:208:27
  65: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/harness.rs:153:15
  66: tokio::runtime::task::raw::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/raw.rs:276:5
  67: tokio::runtime::task::raw::RawTask::poll
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/raw.rs:200:18
  68: tokio::runtime::task::UnownedTask<S>::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/task/mod.rs:437:9
  69: tokio::runtime::blocking::pool::Task::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/blocking/pool.rs:159:9
  70: tokio::runtime::blocking::pool::Inner::run
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/blocking/pool.rs:513:17
  71: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.32.1/src/runtime/blocking/pool.rs:471:13
  72: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys_common/backtrace.rs:154:18
  73: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:529:17
  74: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/panic/unwind_safe.rs:271:9
  75: std::panicking::try::do_call
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:504:40
  76: __rust_try
  77: std::panicking::try
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panicking.rs:468:19
  78: std::panic::catch_unwind
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/panic.rs:142:14
  79: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/thread/mod.rs:528:30
  80: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/core/src/ops/function.rs:250:5
  81: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  82: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/alloc/src/boxed.rs:2007:9
  83: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a28077b28a02b92985b3a3faecf92813155f1ea1/library/std/src/sys/unix/thread.rs:108:17
  84: <unknown>
  85: <unknown>

/tmp/just-vt1ic0/coordinator: line 293:  4179 Aborted                 (core dumped) cargo run --bin coordinator --
error: Recipe `coordinator` failed with exit code 134
```

**Comment by bonomat** [comment]
I hate to say this, but this is just Bitcoin regtest. Potentially this is because we are mining blocks too fast
