### ISSUE TITLE
Send on-chain funds produces multiple `OutputBelowDustLimit` Errors

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#2190]
Environment: test

It seems the transaction got broadcasted, but at the same time we see the following error messages in the logs.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, OutputBelowDustLimit(0), null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      WalletService.calculateFeesForOnChain (package:get_10101/features/wallet/application/wallet_service.dart:54:18)
<asynchronous suspension>
#3      _SendOnChainScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:get_10101/features/wallet/send/send_onchain_screen.dart:194:47)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, OutputBelowDustLimit(0), null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      WalletService.calculateFeesForOnChain (package:get_10101/features/wallet/application/wallet_service.dart:54:18)
<asynchronous suspension>
#3      _SendOnChainScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:get_10101/features/wallet/send/send_onchain_screen.dart:194:47)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FfiException(RESULT_ERROR, OutputBelowDustLimit(0), null)
#0      FlutterRustBridgeBase._transformRust2DartMessage (package:flutter_rust_bridge/src/basic.dart:129:9)
#1      FlutterRustBridgeBase.executeNormal.<anonymous closure> (package:flutter_rust_bridge/src/basic.dart:70:9)
<asynchronous suspension>
#2      WalletService.calculateFeesForOnChain (package:get_10101/features/wallet/application/wallet_service.dart:54:18)
<asynchronous suspension>
#3      _SendOnChainScreenState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:get_10101/features/wallet/send/send_onchain_screen.dart:194:47)
<asynchronous suspension>
```

**Comment by holzeis** [comment]
The error is thrown when entering an amount on the `send_on_chain_screen.dart`.
