### ISSUE TITLE
Panic at not enough outbound capacity to establish given contract

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#340]
**Environment:** VM Testnet
**Build:** 48 (1eff73c111ddc8db9d1204efe3336e401bac1315)

Funded the wallet with 56,321 sats and opened and tried to open a position of leverage 2 with a margin about 41,600 sats. 

Since the coordinator always goes with leverage 1, it has to pay twice the margin (about 83,200 sats), which results into the coordinator not having enough liquidity for the trade in the channel (as the coordinator always has exactly as much sats outbound as it has inbound - initially).

```
2023-03-27 17:47:42 ERROR coordinator::orderbook::trading: Could not notify maker - we should fail here and get another match if possible
2023-03-27 17:47:42 DEBUG coordinator::orderbook::trading: Successfully notified taker
2023-03-27 17:47:43  INFO coordinator::node: Opening position
2023-03-27 17:47:43 DEBUG coordinator::node: Proposing dlc channel event_id="btcusd1680544062"
2023-03-27 17:47:43 DEBUG reqwest::connect: starting new connection: https://oracle.holzeis.me/    
2023-03-27 17:47:44 ERROR coordinator: Aborting after panic in task info=panicked at 'called `Result::unwrap()` on an `Err` value: InvalidParameters("Not enough outbound capacity to establish given contract. Want 83227000 but have 56321000")', /home/runner/work/10101/10101/crates/ln-dlc-node/src/node/dlc_channel.rs:46:14
   0: coordinator::main::{{closure}}::{{closure}}
   1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:2002:9
   2: std::panicking::rust_panic_with_hook
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:692:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
   5: rust_begin_unwind
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   6: core::panicking::panic_fmt
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   7: core::result::unwrap_failed
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   8: <F as axum::handler::Handler<(M,T1,T2),S,B>>::call::{{closure}}
   9: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  10: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  11: <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll
  12: <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll
  13: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop
  14: hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch
  15: <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll
  16: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  17: tokio::runtime::task::core::Core<T,S>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run
  21: tokio::macros::scoped_tls::ScopedKey<T>::set
  22: tokio::runtime::scheduler::multi_thread::worker::run
  23: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  24: tokio::runtime::task::core::Core<T,S>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  30: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  31: std::sys::unix::thread::Thread::new::thread_start
             at ./rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  32: <unknown>
  33: __clone
```

**Comment by holzeis** [comment]
Besides the panic that killed the coordinator, this also highlights a different issue. Eventually we need to limit the user to post a trade with a (margin * leverage) larger than the outbound liquidity of the coordinator. This could become a little bit hard to understand for the user if he is also using the wallet to send and receive sats - as this will impact outbound / inbound balances.

I don't think this is something we have to address right away, but should be probably thought about.

cc @bonomat @da-kami

**Comment by holzeis** [comment]
Is there a reason why the coordinator should not take the same leverage as the trader? If the coordinator always goes with leverage 1 we will have to provide significantly more liquidity.

**Comment by bonomat** [comment]
Ideally we can add additionally liquidity to the channel if needed (aka splice-in) but this is not yet implemented in LDK. - (And also take liquidity of the channel if not needed anymore (splice-out))

> Is there a reason why the coordinator should not take the same leverage as the trader? 

It's a fair question: we decided to go for leverage of 1 for the coordinator due to two reasons :
1. we don't get easily liquidated
2. the trader can actually _win_ the money they are supposed to - i.e. if we get liquidated early, the trader may miss out of his well deserved sats. 

> If the coordinator always goes with leverage 1 we will have to provide significantly more liquidity.

Yes, this is indeed a challenge.

**Comment by holzeis** [comment]
This should have been fixed with https://github.com/get10101/10101/pull/464. Closing this ticket. Please reopen if this error still happens.
