### ISSUE TITLE
Panic at asserting block height

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#783]
After running just fund the coordinator, maker and app crashed at the same time with the same panic. (see below)

This fix seem to have not fixed the issue https://github.com/p2pderivatives/rust-dlc/pull/112.

Interestingly, on the local setup we don't even mine any blocks. 🤔 

```
2023-06-15 13:21:58 DEBUG lightning::ln::peer_handler: Broadcasting NodeAnnouncement after passing it to our own RoutingMessageHandler.    
2023-06-15 13:21:58 ERROR coordinator: Aborting after panic in task info=panicked at 'assertion failed: `(left == right)`
  left: `136`,
 right: `106`', /Users/holzeis/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/chain_monitor.rs:118:9
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/backtrace.rs:332:13
   3: coordinator::main::{{closure}}::{{closure}}
             at ./coordinator/src/bin/coordinator.rs:41:29
   4: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1987:9
   5: std::panicking::rust_panic_with_hook
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:695:13
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:582:13
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:150:18
   8: rust_begin_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:578:5
   9: core::panicking::panic_fmt
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:67:14
  10: core::panicking::assert_failed_inner
  11: core::panicking::assert_failed
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panicking.rs:228:5
  12: dlc_manager::chain_monitor::ChainMonitor::process_block
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/chain_monitor.rs:118:9
  13: dlc_manager::manager::Manager<W,B,S,O,T,F>::check_for_watched_tx
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/manager.rs:2220:29
  14: dlc_manager::manager::Manager<W,B,S,O,T,F>::channel_checks
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/manager.rs:1899:9
  15: dlc_manager::manager::Manager<W,B,S,O,T,F>::periodic_check
             at /Users/holzeis/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/manager.rs:355:9
  16: ln_dlc_node::node::dlc_channel::dlc_manager_periodic_check::{{closure}}::{{closure}}
             at ./crates/ln-dlc-node/src/node/dlc_channel.rs:264:28
  17: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/task.rs:42:21
  18: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.37/src/instrument.rs:272:9
  19: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:223:17
  20: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/loom/std/unsafe_cell.rs:14:9
  21: tokio::runtime::task::core::Core<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/core.rs:212:13
  22: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:476:19
  23: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  24: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  25: ___rust_try
  26: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  27: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  28: tokio::runtime::task::harness::poll_future
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:464:18
  29: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:198:27
  30: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/harness.rs:152:15
  31: tokio::runtime::task::raw::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:255:5
  32: tokio::runtime::task::raw::RawTask::poll
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/raw.rs:200:18
  33: tokio::runtime::task::UnownedTask<S>::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/task/mod.rs:431:9
  34: tokio::runtime::blocking::pool::Task::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:159:9
  35: tokio::runtime::blocking::pool::Inner::run
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:513:17
  36: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /Users/holzeis/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.28.2/src/runtime/blocking/pool.rs:471:13
  37: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys_common/backtrace.rs:134:18
  38: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:526:17
  39: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/panic/unwind_safe.rs:271:9
  40: std::panicking::try::do_call
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:485:40
  41: ___rust_try
  42: std::panicking::try
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:449:19
  43: std::panic::catch_unwind
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panic.rs:140:14
  44: std::thread::Builder::spawn_unchecked_::{{closure}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/thread/mod.rs:525:30
  45: core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/core/src/ops/function.rs:250:5
  46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  47: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/alloc/src/boxed.rs:1973:9
  48: std::sys::unix::thread::Thread::new::thread_start
             at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/sys/unix/thread.rs:108:17
  49: __pthread_joiner_wake
```

**Comment by holzeis** [comment]
It looks like this panic is happening regularly.. the mainnet test_coordinator panicked again at.

```
{"timestamp":"2023-06-15T18:03:16.265593188Z","level":"ERROR","fields":{"message":"Aborting after panic in task","info":"panicked at 'assertion failed: `(left == right)`\n  left: `794489`,\n right: `794488`', /home/runner/.cargo/git/checkouts/rust-dlc-a64d07927f5f2439/3b277dc/dlc-manager/src/chain_monitor.rs:118:9"},"target":"coordinator"}
```

**Comment by holzeis** [comment]
The `sub_channel_manager` and the `manager` are both processing the block for watch transactions. Both increment the `last_height`. This leads to race conditions in which case, we sometimes fail on the block height assertion.

related to #790.
