### ISSUE TITLE
Improve dev environment setup documentation

### ISSUE THREAD

**Issue by holzeis** [get10101/10101#801]
This ticket is to improve our existing dev environment setup documentation.

**Comment by holzeis** [comment]
@Restioson since you are going through your dev environment setup, would be great if you could take over that ticket and add the missing documentation to make it work.

**Comment by Restioson** [comment]
So far it seems to be working for me, bar #802, issues relating to old state (from an ancient version of the project), and a rustup issue.

> A user reached out to us on telegram asking if there is somewhere a better documentation as he failed to start the project on his machine.

Could he elaborate on what the error was so I can investigate?

**Comment by pinhopro** [comment]
When I run just all, I get this error 

```
$ just all
docker-compose up -d
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests/adapters.py", line 439, in send
  File "urllib3/connectionpool.py", line 726, in urlopen
  File "urllib3/util/retry.py", line 410, in increment
  File "urllib3/packages/six.py", line 734, in reraise
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker/api/client.py", line 214, in _retrieve_server_version
  File "docker/api/daemon.py", line 181, in version
  File "docker/utils/decorators.py", line 46, in inner
  File "docker/api/client.py", line 237, in _get
  File "requests/sessions.py", line 543, in get
  File "requests/sessions.py", line 530, in request
  File "requests/sessions.py", line 643, in send
  File "requests/adapters.py", line 498, in send
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 200, in perform_command
  File "compose/cli/command.py", line 60, in project_from_options
  File "compose/cli/command.py", line 152, in get_project
  File "compose/cli/docker_client.py", line 41, in get_client
  File "compose/cli/docker_client.py", line 170, in docker_client
  File "docker/api/client.py", line 197, in __init__
  File "docker/api/client.py", line 221, in _retrieve_server_version
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', ConnectionRefusedError(61, 'Connection refused'))
[26659] Failed to execute script docker-compose
error: Recipe `docker` failed on line 194 with exit code 255
```

**Comment by pinhopro** [comment]
I guess the documentation should be updated to include docker as requirement.

**Comment by klochowicz** [comment]
@pinhopro I made it clear that Docker is a prerequisite: https://github.com/get10101/10101/pull/806

**Comment by klochowicz** [comment]
@Restioson I have created #812 as I was working on a reproducing a bug that needed to shorten the dev cycle - hopefully it helps too!

**Comment by holzeis** [comment]
Closing this ticket as @pinhopro was able to setup the dev environment. Please open another ticket if the documentation has to be improved.
